### ISSUE TITLE
[BUG] Google Auth doesn't work as a expected 

### ISSUE THREAD

**Issue by silverbryan** [JoaquinBeceiro/bills-tracker#116]
![Screenshot_20230420-132204](https://user-images.githubusercontent.com/50382234/233429134-4700ab7c-24a2-46f6-b065-bb1e165f2ddb.png)

**Comment by JoaquinBeceiro** [comment]
Hola! Gracias por el report.
Podrían ser varias razones:
1. El documento debe ser tuyo o te lo tienen que haber compartido con permisos de lectura/escritura
2. El `'` en el nombre no lo probé aún
3. Intentá agregar solamente el ID de la spreadsheet en vez de la full-url, quizás hay algún caracter extraño
Si tu URL es `https://docs.google.com/spreadsheets/d/14RDVe4-2-E44n7IVCCZ2waXBE4557ZD3Node-EPPd0/edit#gid=0`, intenta solamente con la parte de https://docs.google.com/spreadsheets/d/`14RDVe4-2-E44n7IVCCZ2waXBE4557ZD3Node-EPPd0`/edit#gid=0
